// Bundles the MCP App chart view (mcp-app/chart-view.ts) into one
// self-contained HTML page and writes it as a TypeScript string module,
// lib/mcp-app/chart-view-html.generated.ts, which the MCP server serves as the
// ui://financeplots/charts.html resource. Inline on purpose: hosts sandbox the
// view, and an inline page needs no CSP allowance for any domain.
//
// Runs before dev, build and test (npm pre-scripts). The output is generated
// and gitignored — edit mcp-app/, not the output.

import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "lib/mcp-app/chart-view-html.generated.ts");

const result = await build({
  entryPoints: [resolve(root, "mcp-app/chart-view.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
  legalComments: "none",
  tsconfig: resolve(root, "tsconfig.json"),
  logLevel: "warning",
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");

const css = `
:root { color-scheme: light dark; --bg: #ffffff; --text: #0f172a; --text2: #475569; --line: #e2e8f0; --tip: #ffffff; }
:root[data-theme="dark"] { --bg: #0d1426; --text: #e2e8f0; --text2: #94a3b8; --line: #1e293b; --tip: #111a30; }
* { box-sizing: border-box; }
html, body { margin: 0; background: transparent; overflow: hidden; } /* the host sizes the frame to the content */
body { font-family: var(--font-sans, var(--font)); color: var(--text); font-size: 13px; }
#root { display: flex; flex-direction: column; gap: 12px; }
.card { background: var(--bg); border-radius: 12px; overflow: hidden; }
.frame { position: relative; }
.frame svg:focus-visible { outline: 2px solid #3987e5; outline-offset: -2px; }
.tip { position: absolute; min-width: 150px; max-width: 260px; padding: 8px 10px; border-radius: 8px; background: var(--tip);
  border: 1px solid var(--line); box-shadow: 0 4px 16px rgb(0 0 0 / 0.18); pointer-events: none; font-size: 12px; }
.tip-title { font-weight: 600; margin-bottom: 4px; }
.row { display: flex; align-items: center; gap: 6px; line-height: 1.6; }
.sw { width: 8px; height: 8px; border-radius: 2px; flex: none; }
.name { color: var(--text2); flex: 1; }
.val { font-variant-numeric: tabular-nums; font-weight: 600; }
.actions { display: flex; justify-content: flex-end; padding: 0 12px 10px; }
.toggle { font: inherit; font-size: 12px; color: var(--text2); background: none; border: 1px solid var(--line); border-radius: 6px; padding: 3px 10px; cursor: pointer; }
.toggle:hover { color: var(--text); }
.table-wrap { max-height: 280px; overflow: auto; padding: 0 12px 12px; }
table { border-collapse: collapse; width: 100%; font-size: 12px; font-variant-numeric: tabular-nums; }
caption { text-align: left; color: var(--text2); padding: 4px 0; }
th, td { padding: 4px 8px; border-bottom: 1px solid var(--line); text-align: right; white-space: nowrap; }
th:first-child { text-align: left; }
thead th { position: sticky; top: 0; background: var(--bg); color: var(--text2); font-weight: 600; }
.message { color: var(--text2); padding: 16px; margin: 0; }
`;

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FinancePlots chart</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${js}</script>
</body>
</html>`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/build-mcp-app.mjs from mcp-app/chart-view.ts. Do not edit.\n` +
    `export const CHART_VIEW_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`mcp-app: wrote ${out.replace(root, ".")} (${(html.length / 1024).toFixed(0)} KB)`);
